behaviors:
  PacmanMlAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 1024
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 1.0
        demo_path: Demos/PacmanAgentDemo.demo
    behavioral/cloning:
        strength: 0.5
	demo_path: Demos/PacmanAgentDemo.demo
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1500
    summary_freq: 100000
    threaded: true